/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.stalostech.jooq.tables.Car;
import pl.stalostech.jooq.tables.CarClient;
import pl.stalostech.jooq.tables.CarType;
import pl.stalostech.jooq.tables.Client;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jpavsnative extends SchemaImpl {

	private static final long serialVersionUID = -770814417;

	/**
	 * The reference instance of <code>jpavsnative</code>
	 */
	public static final Jpavsnative JPAVSNATIVE = new Jpavsnative();

	/**
	 * No further instances allowed
	 */
	private Jpavsnative() {
		super("jpavsnative");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.CAR_ID_SEQ,
			Sequences.CAR_TYPE_ID_SEQ,
			Sequences.CLIENT_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Car.CAR,
			CarClient.CAR_CLIENT,
			CarType.CAR_TYPE,
			Client.CLIENT);
	}
}
