/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import pl.stalostech.jooq.tables.Car;
import pl.stalostech.jooq.tables.CarClient;
import pl.stalostech.jooq.tables.CarType;
import pl.stalostech.jooq.tables.Client;
import pl.stalostech.jooq.tables.records.CarClientRecord;
import pl.stalostech.jooq.tables.records.CarRecord;
import pl.stalostech.jooq.tables.records.CarTypeRecord;
import pl.stalostech.jooq.tables.records.ClientRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>jpavsnative</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<CarRecord, Integer> IDENTITY_CAR = Identities0.IDENTITY_CAR;
	public static final Identity<CarTypeRecord, Integer> IDENTITY_CAR_TYPE = Identities0.IDENTITY_CAR_TYPE;
	public static final Identity<ClientRecord, Integer> IDENTITY_CLIENT = Identities0.IDENTITY_CLIENT;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CarRecord> CAR_PKEY = UniqueKeys0.CAR_PKEY;
	public static final UniqueKey<CarTypeRecord> CARTYPE_PKEY = UniqueKeys0.CARTYPE_PKEY;
	public static final UniqueKey<ClientRecord> CLIENT_PKEY = UniqueKeys0.CLIENT_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<CarRecord, CarTypeRecord> CAR__CARTOCARTYPE = ForeignKeys0.CAR__CARTOCARTYPE;
	public static final ForeignKey<CarClientRecord, CarRecord> CAR_CLIENT__CARIDFOREIGN = ForeignKeys0.CAR_CLIENT__CARIDFOREIGN;
	public static final ForeignKey<CarClientRecord, ClientRecord> CAR_CLIENT__CLIENTIDFOREIGN = ForeignKeys0.CAR_CLIENT__CLIENTIDFOREIGN;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<CarRecord, Integer> IDENTITY_CAR = createIdentity(Car.CAR, Car.CAR.ID);
		public static Identity<CarTypeRecord, Integer> IDENTITY_CAR_TYPE = createIdentity(CarType.CAR_TYPE, CarType.CAR_TYPE.ID);
		public static Identity<ClientRecord, Integer> IDENTITY_CLIENT = createIdentity(Client.CLIENT, Client.CLIENT.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CarRecord> CAR_PKEY = createUniqueKey(Car.CAR, Car.CAR.ID);
		public static final UniqueKey<CarTypeRecord> CARTYPE_PKEY = createUniqueKey(CarType.CAR_TYPE, CarType.CAR_TYPE.ID);
		public static final UniqueKey<ClientRecord> CLIENT_PKEY = createUniqueKey(Client.CLIENT, Client.CLIENT.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<CarRecord, CarTypeRecord> CAR__CARTOCARTYPE = createForeignKey(pl.stalostech.jooq.Keys.CARTYPE_PKEY, Car.CAR, Car.CAR.CAR_TYPE);
		public static final ForeignKey<CarClientRecord, CarRecord> CAR_CLIENT__CARIDFOREIGN = createForeignKey(pl.stalostech.jooq.Keys.CAR_PKEY, CarClient.CAR_CLIENT, CarClient.CAR_CLIENT.CAR_ID);
		public static final ForeignKey<CarClientRecord, ClientRecord> CAR_CLIENT__CLIENTIDFOREIGN = createForeignKey(pl.stalostech.jooq.Keys.CLIENT_PKEY, CarClient.CAR_CLIENT, CarClient.CAR_CLIENT.CLIENT_ID);
	}
}
