/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq;


import javax.annotation.Generated;

import org.jooq.Configuration;

import pl.stalostech.jooq.routines.TruncateTables;


/**
 * Convenience access to all stored procedures and functions in jpavsnative
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>jpavsnative.truncate_tables</code>
	 */
	public static void truncateTables(Configuration configuration) {
		TruncateTables p = new TruncateTables();

		p.execute(configuration);
	}
}
