/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq;


import javax.annotation.Generated;

import pl.stalostech.jooq.tables.Car;
import pl.stalostech.jooq.tables.CarClient;
import pl.stalostech.jooq.tables.CarType;
import pl.stalostech.jooq.tables.Client;


/**
 * Convenience access to all tables in jpavsnative
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jpavsnative.car
	 */
	public static final Car CAR = pl.stalostech.jooq.tables.Car.CAR;

	/**
	 * The table jpavsnative.car_client
	 */
	public static final CarClient CAR_CLIENT = pl.stalostech.jooq.tables.CarClient.CAR_CLIENT;

	/**
	 * The table jpavsnative.car_type
	 */
	public static final CarType CAR_TYPE = pl.stalostech.jooq.tables.CarType.CAR_TYPE;

	/**
	 * The table jpavsnative.client
	 */
	public static final Client CLIENT = pl.stalostech.jooq.tables.Client.CLIENT;
}
