/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;

import pl.stalostech.jooq.tables.GetTestingMultijoinDataByRegnrAndSurname;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetTestingMultijoinDataByRegnrAndSurnameRecord extends TableRecordImpl<GetTestingMultijoinDataByRegnrAndSurnameRecord> implements Record8<String, String, Integer, String, Timestamp, Integer, String, Timestamp> {

	private static final long serialVersionUID = -1484722250;

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.surname</code>.
	 */
	public void setSurname(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.surname</code>.
	 */
	public String getSurname() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.carid</code>.
	 */
	public void setCarid(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.carid</code>.
	 */
	public Integer getCarid() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.registrationnr</code>.
	 */
	public void setRegistrationnr(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.registrationnr</code>.
	 */
	public String getRegistrationnr() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.productionyear</code>.
	 */
	public void setProductionyear(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.productionyear</code>.
	 */
	public Timestamp getProductionyear() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.doors</code>.
	 */
	public void setDoors(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.doors</code>.
	 */
	public Integer getDoors() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.model</code>.
	 */
	public void setModel(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.model</code>.
	 */
	public String getModel() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.availableyear</code>.
	 */
	public void setAvailableyear(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>jpavsnative.get_testing_multijoin_data_by_regnr_and_surname.availableyear</code>.
	 */
	public Timestamp getAvailableyear() {
		return (Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, Integer, String, Timestamp, Integer, String, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, Integer, String, Timestamp, Integer, String, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.SURNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.CARID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.REGISTRATIONNR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.PRODUCTIONYEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.DOORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME.AVAILABLEYEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSurname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCarid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getRegistrationnr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getProductionyear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getDoors();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getAvailableyear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value2(String value) {
		setSurname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value3(Integer value) {
		setCarid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value4(String value) {
		setRegistrationnr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value5(Timestamp value) {
		setProductionyear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value6(Integer value) {
		setDoors(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value7(String value) {
		setModel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord value8(Timestamp value) {
		setAvailableyear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GetTestingMultijoinDataByRegnrAndSurnameRecord values(String value1, String value2, Integer value3, String value4, Timestamp value5, Integer value6, String value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GetTestingMultijoinDataByRegnrAndSurnameRecord
	 */
	public GetTestingMultijoinDataByRegnrAndSurnameRecord() {
		super(GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME);
	}

	/**
	 * Create a detached, initialised GetTestingMultijoinDataByRegnrAndSurnameRecord
	 */
	public GetTestingMultijoinDataByRegnrAndSurnameRecord(String name, String surname, Integer carid, String registrationnr, Timestamp productionyear, Integer doors, String model, Timestamp availableyear) {
		super(GetTestingMultijoinDataByRegnrAndSurname.GET_TESTING_MULTIJOIN_DATA_BY_REGNR_AND_SURNAME);

		setValue(0, name);
		setValue(1, surname);
		setValue(2, carid);
		setValue(3, registrationnr);
		setValue(4, productionyear);
		setValue(5, doors);
		setValue(6, model);
		setValue(7, availableyear);
	}
}
