/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.h2;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import pl.stalostech.jooq.h2.tables.Cartype;
import pl.stalostech.jooq.h2.tables.records.CartypeRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<CartypeRecord, Integer> IDENTITY_CARTYPE = Identities0.IDENTITY_CARTYPE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CartypeRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<CartypeRecord, Integer> IDENTITY_CARTYPE = createIdentity(Cartype.CARTYPE, Cartype.CARTYPE.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CartypeRecord> CONSTRAINT_4 = createUniqueKey(Cartype.CARTYPE, Cartype.CARTYPE.ID);
	}
}
