/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.h2;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_206AB42F_E5AA_4B7D_96C2_AA77FAA79C9A</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_206AB42F_E5AA_4B7D_96C2_AA77FAA79C9A = new SequenceImpl<Long>("SYSTEM_SEQUENCE_206AB42F_E5AA_4B7D_96C2_AA77FAA79C9A", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
