/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.h2;


import javax.annotation.Generated;

import pl.stalostech.jooq.h2.tables.Cartype;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.CARTYPE
	 */
	public static final Cartype CARTYPE = pl.stalostech.jooq.h2.tables.Cartype.CARTYPE;
}
