/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.routines;


import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;

import pl.stalostech.jooq.Jpavsnative;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TruncateTables extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -282129863;

	/**
	 * Create a new routine call instance
	 */
	public TruncateTables() {
		super("truncate_tables", Jpavsnative.JPAVSNATIVE);
	}
}
