/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import pl.stalostech.jooq.Jpavsnative;
import pl.stalostech.jooq.Keys;
import pl.stalostech.jooq.tables.records.CarRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Car extends TableImpl<CarRecord> {

	private static final long serialVersionUID = -1735268550;

	/**
	 * The reference instance of <code>jpavsnative.car</code>
	 */
	public static final Car CAR = new Car();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CarRecord> getRecordType() {
		return CarRecord.class;
	}

	/**
	 * The column <code>jpavsnative.car.id</code>.
	 */
	public final TableField<CarRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jpavsnative.car.car_type</code>.
	 */
	public final TableField<CarRecord, Integer> CAR_TYPE = createField("car_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jpavsnative.car.registration_nr</code>.
	 */
	public final TableField<CarRecord, String> REGISTRATION_NR = createField("registration_nr", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>jpavsnative.car.production_year</code>.
	 */
	public final TableField<CarRecord, Timestamp> PRODUCTION_YEAR = createField("production_year", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>jpavsnative.car</code> table reference
	 */
	public Car() {
		this("car", null);
	}

	/**
	 * Create an aliased <code>jpavsnative.car</code> table reference
	 */
	public Car(String alias) {
		this(alias, CAR);
	}

	private Car(String alias, Table<CarRecord> aliased) {
		this(alias, aliased, null);
	}

	private Car(String alias, Table<CarRecord> aliased, Field<?>[] parameters) {
		super(alias, Jpavsnative.JPAVSNATIVE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CarRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CarRecord> getPrimaryKey() {
		return Keys.CAR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CarRecord>> getKeys() {
		return Arrays.<UniqueKey<CarRecord>>asList(Keys.CAR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<CarRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<CarRecord, ?>>asList(Keys.CAR__CARTOCARTYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Car as(String alias) {
		return new Car(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Car rename(String name) {
		return new Car(name, null);
	}
}
