/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import pl.stalostech.jooq.Jpavsnative;
import pl.stalostech.jooq.Keys;
import pl.stalostech.jooq.tables.records.ClientRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client extends TableImpl<ClientRecord> {

	private static final long serialVersionUID = 1929987199;

	/**
	 * The reference instance of <code>jpavsnative.client</code>
	 */
	public static final Client CLIENT = new Client();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ClientRecord> getRecordType() {
		return ClientRecord.class;
	}

	/**
	 * The column <code>jpavsnative.client.id</code>.
	 */
	public final TableField<ClientRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jpavsnative.client.name</code>.
	 */
	public final TableField<ClientRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>jpavsnative.client.surname</code>.
	 */
	public final TableField<ClientRecord, String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>jpavsnative.client</code> table reference
	 */
	public Client() {
		this("client", null);
	}

	/**
	 * Create an aliased <code>jpavsnative.client</code> table reference
	 */
	public Client(String alias) {
		this(alias, CLIENT);
	}

	private Client(String alias, Table<ClientRecord> aliased) {
		this(alias, aliased, null);
	}

	private Client(String alias, Table<ClientRecord> aliased, Field<?>[] parameters) {
		super(alias, Jpavsnative.JPAVSNATIVE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ClientRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CLIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ClientRecord> getPrimaryKey() {
		return Keys.CLIENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ClientRecord>> getKeys() {
		return Arrays.<UniqueKey<ClientRecord>>asList(Keys.CLIENT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Client as(String alias) {
		return new Client(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Client rename(String name) {
		return new Client(name, null);
	}
}
