/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Car implements Serializable {

	private static final long serialVersionUID = 857340732;

	private Integer   id;
	private Integer   carType;
	private String    registrationNr;
	private Timestamp productionYear;

	public Car() {}

	public Car(Car value) {
		this.id = value.id;
		this.carType = value.carType;
		this.registrationNr = value.registrationNr;
		this.productionYear = value.productionYear;
	}

	public Car(
		Integer   id,
		Integer   carType,
		String    registrationNr,
		Timestamp productionYear
	) {
		this.id = id;
		this.carType = carType;
		this.registrationNr = registrationNr;
		this.productionYear = productionYear;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarType() {
		return this.carType;
	}

	public void setCarType(Integer carType) {
		this.carType = carType;
	}

	public String getRegistrationNr() {
		return this.registrationNr;
	}

	public void setRegistrationNr(String registrationNr) {
		this.registrationNr = registrationNr;
	}

	public Timestamp getProductionYear() {
		return this.productionYear;
	}

	public void setProductionYear(Timestamp productionYear) {
		this.productionYear = productionYear;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Car (");

		sb.append(id);
		sb.append(", ").append(carType);
		sb.append(", ").append(registrationNr);
		sb.append(", ").append(productionYear);

		sb.append(")");
		return sb.toString();
	}
}
