/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarType implements Serializable {

	private static final long serialVersionUID = -1627981755;

	private Integer   id;
	private Integer   doors;
	private String    model;
	private Timestamp availableYear;

	public CarType() {}

	public CarType(CarType value) {
		this.id = value.id;
		this.doors = value.doors;
		this.model = value.model;
		this.availableYear = value.availableYear;
	}

	public CarType(
		Integer   id,
		Integer   doors,
		String    model,
		Timestamp availableYear
	) {
		this.id = id;
		this.doors = doors;
		this.model = model;
		this.availableYear = availableYear;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDoors() {
		return this.doors;
	}

	public void setDoors(Integer doors) {
		this.doors = doors;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Timestamp getAvailableYear() {
		return this.availableYear;
	}

	public void setAvailableYear(Timestamp availableYear) {
		this.availableYear = availableYear;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CarType (");

		sb.append(id);
		sb.append(", ").append(doors);
		sb.append(", ").append(model);
		sb.append(", ").append(availableYear);

		sb.append(")");
		return sb.toString();
	}
}
