/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client implements Serializable {

	private static final long serialVersionUID = -293166458;

	private Integer id;
	private String  name;
	private String  surname;

	public Client() {}

	public Client(Client value) {
		this.id = value.id;
		this.name = value.name;
		this.surname = value.surname;
	}

	public Client(
		Integer id,
		String  name,
		String  surname
	) {
		this.id = id;
		this.name = name;
		this.surname = surname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Client (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(surname);

		sb.append(")");
		return sb.toString();
	}
}
