/**
 * This class is generated by jOOQ
 */
package pl.stalostech.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetTestingMultijoinDataByRegnrAndSurname implements Serializable {

	private static final long serialVersionUID = -606383505;

	private String    name;
	private String    surname;
	private Integer   carid;
	private String    registrationnr;
	private Timestamp productionyear;
	private Integer   doors;
	private String    model;
	private Timestamp availableyear;

	public GetTestingMultijoinDataByRegnrAndSurname() {}

	public GetTestingMultijoinDataByRegnrAndSurname(GetTestingMultijoinDataByRegnrAndSurname value) {
		this.name = value.name;
		this.surname = value.surname;
		this.carid = value.carid;
		this.registrationnr = value.registrationnr;
		this.productionyear = value.productionyear;
		this.doors = value.doors;
		this.model = value.model;
		this.availableyear = value.availableyear;
	}

	public GetTestingMultijoinDataByRegnrAndSurname(
		String    name,
		String    surname,
		Integer   carid,
		String    registrationnr,
		Timestamp productionyear,
		Integer   doors,
		String    model,
		Timestamp availableyear
	) {
		this.name = name;
		this.surname = surname;
		this.carid = carid;
		this.registrationnr = registrationnr;
		this.productionyear = productionyear;
		this.doors = doors;
		this.model = model;
		this.availableyear = availableyear;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Integer getCarid() {
		return this.carid;
	}

	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	public String getRegistrationnr() {
		return this.registrationnr;
	}

	public void setRegistrationnr(String registrationnr) {
		this.registrationnr = registrationnr;
	}

	public Timestamp getProductionyear() {
		return this.productionyear;
	}

	public void setProductionyear(Timestamp productionyear) {
		this.productionyear = productionyear;
	}

	public Integer getDoors() {
		return this.doors;
	}

	public void setDoors(Integer doors) {
		this.doors = doors;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Timestamp getAvailableyear() {
		return this.availableyear;
	}

	public void setAvailableyear(Timestamp availableyear) {
		this.availableyear = availableyear;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("GetTestingMultijoinDataByRegnrAndSurname (");

		sb.append(name);
		sb.append(", ").append(surname);
		sb.append(", ").append(carid);
		sb.append(", ").append(registrationnr);
		sb.append(", ").append(productionyear);
		sb.append(", ").append(doors);
		sb.append(", ").append(model);
		sb.append(", ").append(availableyear);

		sb.append(")");
		return sb.toString();
	}
}
